[project]
name = "msc"
version = "0.1.0"
description = "a project"
readme = "README.md"
authors = [
    {name = "Viggo Gascou", email = "viga@itu.dk"},
    {name = "Erling Amundsen", email = "erla@itu.dk"},
]

requires-python = ">=3.12,<3.13"
dependencies = [
    "accelerate>=1.13.0",
    "diffusers>=0.37.0",
    "h5py>=3.16.0",
    "insightface>=0.7.3",
    "loguru>=0.7.3",
    "numpy>=2.4.2",
    "omegaconf>=2.3.0",
    "onnxruntime>=1.24.3 ; sys_platform == 'darwin'",
    "onnxruntime-gpu>=1.24.3 ; sys_platform == 'linux'",
    "pandas>=3.0.2",
    "peft>=0.18.1",
    "pyarrow>=23.0.1",
    "python-dotenv>=1.2.2",
    "scikit-learn>=1.8.0",
    "torch==2.10.0",
    "torchvision==0.25.0",
    "transformers>=5.3.0",
    "tyro>=1.0.6",
    "wandb>=0.25.1",
]

[project.urls]
Repository = "https://github.com/viggo-gascou/msc"
Issues = "https://github.com/viggo-gascou/msc/issues"

[project.license]
file = "LICENSE"

[dependency-groups]
dev = [
    "pre-commit>=4.3.0",
    "click>=8.2.1",
    "ruff>=0.15.1",
    "pyrefly>=0.52.0",
    "nbstripout>=0.9.0",
    "pip>=26.1",
    "ipykernel>=7.2.0",
    "jupyter>=1.1.1",
]

[tool.uv.sources]
torch = [
  { index = "pytorch", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]
torchvision = [
  { index = "pytorch", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]

[[tool.uv.index]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cu126"
explicit = true

[tool.uv]
default-groups = []

[project.scripts]
train = "scripts.train:train"
inference = "scripts.inference:inference"

[tool.ruff]
target-version = "py312"
line-length = 88
exclude = [
    ".git",
    ".ruff_cache",
    ".venv",
]
extend-include = [
    "*.ipynb",
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
docstring-code-format = true
skip-magic-trailing-comma = true

[tool.ruff.lint]
preview = true
select = [
    # isort (imports)
    "I",
    # Docstrings
    "D",
    "DOC",
    # pycodestyle errors and warnings (PEP8)
    "E",
    "W",
    # flake-annotations (type hints)
    "ANN",
    # Pyflakes
    "F",
]
ignore = [
    # Type annotations for "self" arguments
    "ANN101",
    # Type annotations for "cls" arguments
    "ANN102",
    # Type annotations for *args
    "ANN002",
    # Type annotations for **kwargs
    "ANN003",
]

[tool.ruff.lint.extend-per-file-ignores]
"__init__.py" = [
    "F401",
]
"src/scripts/main.py" = [
    "I",
]

[tool.ruff.lint.isort]
split-on-trailing-comma = false
known-first-party = ["msc"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.pyrefly.errors]
missing-import = false
missing-attribute = false
not-iterable = false
no-matching-overload = false

[tool.pyrefly]
site-package-path = [".venv/lib/python3.12/site-packages"]
project-excludes = ["src/scripts"]


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
