#!/bin/bash

#SBATCH --job-name=libreface
#SBATCH --output=logs/SLURM/libreface.%j.out
#SBATCH --cpus-per-task=8
#SBATCH --mem-per-cpu=8G
#SBATCH --gres=gpu:a30:1
#SBATCH --time=12:00:00
#SBATCH --partition=scavenge
#SBATCH --mail-type=BEGIN,END

## SETUP


module load uv/0.7.13-GCCcore-14.2.0
module load CMake/3.27.6-GCCcore-13.2.0
module load Python/3.11.5-GCCcore-13.2.0

# Create a venv using the module loaded Python, only if it doesn't exist
if [ ! -d ".venv-libreface" ]; then
    uv venv --python $(which python3) .venv-libreface

    # Install dependencies from the inline requirements
    uv pip install --python .venv-libreface/bin/python \
        --requirements-from-script src/scripts/libreface_bp4d.py
fi

export OMP_NUM_THREADS=8

# Activate the venv
source .venv-libreface/bin/activate

## RUN

echo "Running on $(hostname) at $(date)"

python src/scripts/libreface_bp4d.py \
    --batch-size 64 \
    --chunk-size 500
SCRIPT_EXIT_CODE=$?

echo "Done, finished at $(date)"
exit $SCRIPT_EXIT_CODE
