#!/bin/bash

#SBATCH --job-name=run
#SBATCH --output=logs/SLURM/run.%j.out
#SBATCH --cpus-per-task=6
#SBATCH --mem-per-cpu=6G
#SBATCH --time=8:00:00
#SBATCH --partition=scavenge
#SBATCH --mail-type=BEGIN,END

## SETUP

# load uv
module load uv/0.7.13-GCCcore-14.2.0

# Set this to match "cpus-per-task", supresses ONNX warning on cpu affinity
export OMP_NUM_THREADS=6

# Disable albumentations to check for updates
export NO_ALBUMENTATIONS_UPDATE=1

## RUN

SCRIPT="$1"
# Run without syncing venv
uv run --no-sync "$SCRIPT"
SCRIPT_EXIT_CODE=$?

echo "Done, finished at $(date)"

exit $SCRIPT_EXIT_CODE
