#!/bin/bash

#SBATCH --job-name=uv-sync
#SBATCH --output=logs/SLURM/sync.%j.out
#SBATCH --cpus-per-task=8
#SBATCH --mem-per-cpu=2G
#SBATCH --time=5:30:00
#SBATCH --nodelist=cn7,cn9,cn10,cn11,cn14,cn15
#SBATCH --partition=scavenge

## SETUP

# load uv
module load uv/0.7.13-GCCcore-14.2.0

export UV_FROZEN=1          # never update lockfile
export UV_NO_DEV=1          # skip dev dependencies

## RUN

echo "Syncing git state at $(date)"
git pull

echo "Syncing uv state at $(date)"
uv sync
UV_EXIT_STATUS=$?

echo "Done, finished at $(date)"
exit $UV_EXIT_STATUS
