#!/bin/bash

#SBATCH --job-name=semedit
#SBATCH --output=logs/SLURM/train.%j.out
#SBATCH --cpus-per-task=6
#SBATCH --mem-per-cpu=6G
#SBATCH --gres=gpu:a30:2
#SBATCH --time=10:00:00
#SBATCH --partition=scavenge
#SBATCH --mail-type=BEGIN,END

## SETUP

# load uv
module load uv/0.7.13-GCCcore-14.2.0

# Never sync venv
export UV_NO_SYNC=1

# Set this to match "cpus-per-task", supresses ONNX warning on cpu affinity
export OMP_NUM_THREADS=6

# Disable albumentations to check for updates
export NO_ALBUMENTATIONS_UPDATE=1

## RUN

echo "Running on $(hostname):"
echo "Using GPU $(nvidia-smi --query-gpu=gpu_name --format=csv,noheader)"

VRAM_TOTAL=$(nvidia-smi --query-gpu=memory.total --format=csv,noheader,nounits | tr -d ' ')
echo "Total GPU RAM: ${VRAM_TOTAL} MiB"

# run the script
uv run accelerate launch --multi_gpu \
    --num_processes 2 \
    --num_machines 1 \
    --mixed_precision bf16 \
    --dynamo_backend no \
    src/scripts/train.py \
    --parameters.dataloader.batch-size 8 \
    --parameters.gradient-accumulation-steps 6 \
    --parameters.gradient-checkpointing
SCRIPT_EXIT=$?

echo "Done, finished at $(date)"
exit $SCRIPT_EXIT
